### ISSUE TITLE
Can't close editor

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1009]
Sometimes editor2 don't close.
I have Defold in dock:
![2017-06-16_12-13-57](https://user-images.githubusercontent.com/2209596/27220287-53bb10a4-528d-11e7-88ac-1878d00a8c9d.png)
I have Defold in Force quit menu:
![2017-06-16_12-14-43](https://user-images.githubusercontent.com/2209596/27220313-66905ee6-528d-11e7-9d2b-d1f978eea081.png)

But Force Quit cannot close Defold. And I can't find it in Activity Monitor:
![2017-06-16_12-15-45](https://user-images.githubusercontent.com/2209596/27220355-8afaf2f0-528d-11e7-8fde-267f350120d7.png)
![2017-06-16_12-16-04](https://user-images.githubusercontent.com/2209596/27220367-94deeaf6-528d-11e7-9215-a3b3de0ad081.png)

It has no window, and cannot close. Of course I can't open new window too. In this situation the one way that i find is restart mac .
and it's not easy:
![2017-06-16_12-24-40](https://user-images.githubusercontent.com/2209596/27220714-cfebb1dc-528e-11e7-86f0-0be7bd0d9e8b.png)

How it reproduces:

I close Defold Editor (When I want to recieve an update for example) then open it and leave for some time on other desktop (but I am not sure, maybe I just close and editor stays in dock)

**Comment by RagnarSvenssonKing** [comment]
This issue has been fixed, but what hasn't been fixed is automatic update of the launcher software (a small C-program that launches the editor). So in order to get this fix, you need to download the editor again. The fix for the automatic update is in progress and being reviewed, so you could also wait until some time next week when the update will probably work again.

**Comment by AGulev** [comment]
Cool! Thank you!
