### ISSUE TITLE
Timing issues on displays not refreshing at 60hz

### ISSUE THREAD

**Issue by ciw1973** [defold/editor2-issues#1061]
I run a 40" 4K TV as a second monitor for my laptop, with a refresh rate of only 30fps, and this is perfectly fine for using various multi-panel IDEs I use like Defold, however...

...if I drag a running Defold game window onto this monitor, everything runs at 50% speed. Drag it back to the laptop display, and it's full speed again. Interestingly, if I even have 1 pixel of the game window on the 30hz screen, then the game runs at half speed.

In the Runner example, the code appears to be using dt correctly, so I'd have expected the overall speed of the game to have remained the same, with the movement just less smooth than on the 60hz display.

In the Alien World example, the same happens, but the scrolling is handled using the animate built in Game Object method with a duration of 20 seconds. On my laptop screen, that's works as expected, but again, it runs at half that speed on the 30hz screen.

These observations suggest that the engine isn't using actual delta time, but rather the number of frames which have passed, and assuming that this is 60fps, meaning that even using dt correctly won't allow movement at a constant speed regardless of display frame rate.

**Comment by RagnarSvenssonKing** [comment]
The reason for this is that we have no software throttling of the game loop yet, instead we rely on the vsync (i.e. assuming it runs at 60hz) to flip frames in the game. Software throttling is a missing feature. If you want to run the game properly on your tv, you can turn on "display > variable dt" in your game.project file. This makes the dt take on the actual time between frames, rather than being hard coded to 1/60. The drawback of a variable dt is that it can make simulations unstable but the conditions have to be quite severe for that to happen, like severe hitches etc.

**Comment by ciw1973** [comment]
Ah, OK. I wasn't aware of the Variable DT option, which I've checked, and it works as expected.
