### ISSUE TITLE
Error for console while building

### ISSUE THREAD

**Issue by DenizTemizer** [defold/editor2-issues#1072]
### Expected behaviour
Debug console running as usual.

### Actual behaviour
Getting this error while building:
`java.lang.NumberFormatException: null`
Hitting Build / Rebuild "helps" and makes the console work some times.
(Build runs perfect and works even with this error.)

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Build time</td><td>2017-07-18T18:26:28.750532</td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>cc5030bb38e30bdbcb423f510247c9e180cb580c</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.13</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=67dcbd3b49ed4554bc0602c377077b6c'>67dcbd3b49ed4554bc0602c377077b6c</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
I believe this error comes from when you trigger a build when a build is already in progress. Since there is no progress visualization yet for builds, this is quite easily done. Does this fit your experience of when the error happens?
We have a fix in progress for this issue, but it requires more testing before it can be merged as it touches many parts of the system. Progress visualization also needs to be fixed so it's clear when a build is in progress and when it's finished.
For now I believe you can avoid this problem by waiting for each build. Please comment if this is not the case.

**Comment by DenizTemizer** [comment]
You are right! This only happens when I already got a build running or a process going.

**Comment by erikangelin-king** [comment]
This has been partially fixed; you should no longer get this error, but there is still no build progress.
