### ISSUE TITLE
Moving gui files in editor folders / moving texture atlases to new folders doesn't update correctly when making copies of files

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1114]
I have to go through and correct all of the texture locations etc.

**Comment by matgis-king** [comment]
I'm not sure I understand the issue completely, but this sounds like the behavior we intended.

When you move a file we will update any references to the moved file, but only if the the reference would be left broken as a result of the move. If you make a copy, the original location remains and we don't consider your intention was to update the references. Often you just want to make a copy of some set-up in order to create a variant to use elsewhere in a project.

Does that explain what happened here?

**Comment by subsoap** [comment]
Yes, I think so. I copy and pasted some files, moved the files the original and copies were referenced to, but I think only the originals had their references kept. I'm not 100% sure I will need to test again to confirm.

**Comment by erikangelin-king** [comment]
Please reopen if it's still not acting as expected!
