### ISSUE TITLE
Confusing Mac Install

### ISSUE THREAD

**Issue by jpz** [defold/editor2-issues#1164]
Hi, I downloaded the DMG, but I'm not presented with an application to drag and drop into Applications, as I would expect.

Instead, I have a top level folder Defold.macosx.cocoa.x86_64 - which has a bunch of stuff inside it, including Defold.app, as well as several other directories.

I clicked on Defold.app to test it (running it in-place), and I get an error.  I can experiment here, but the point I want to raise is that it's non-intuitive - there should be a README or some instructions if you have a non-standard installation process.

Or it could be that the OSX packaging process is broken, of course...

**Comment by ragnard-king** [comment]
Hi @jpz, thanks for the feedback.

It sounds like you've downloaded version 1 of the editor, as this is fixed in version 2.

If you want to try editor2, you can downloaded it from the same place in the dashboard, see the section "Editor 2 Pre-release":

![image](https://user-images.githubusercontent.com/20399970/29808541-dac4cdde-8c98-11e7-91e0-e565f98ba05b.png)

This is what opening the DMG should look like for editor2:

![image](https://user-images.githubusercontent.com/20399970/29808504-ad234ef0-8c98-11e7-8454-272f9862177c.png)

**Comment by jpz** [comment]
You are right, I'm sorry to have troubled you. :)

**Comment by ragnard-king** [comment]
No worries, thank you for giving defold a go. Let us know if you try editor2 and find any obstacles!
