### ISSUE TITLE
Close without save doesn't work.

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1191]
### Expected behaviour
1. Make some changes in file.
2. Close file
3. cmd+s 
4. nothing change
### Actual behaviour
1. Make some changes in any file.
2. Close file
3. cmd+s 
4. file save changes
### Steps to reproduce
1. Make some changes in file.
2. Close file
3. cmd+s 
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Defold sha</td><td>ead5b04fb115bb4a5d9d781b38d580d0fc4783b0</td></tr>
<tr><td>Build time</td><td>2017-09-08T14:12:54.646509</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @AGulev!

I understand this can be unexpected but the behaviour is intentional. The whole project resides in memory in editor 2 and opening/editing an asset is more like opening a particular view into the project. The changes you make can touch several assets, and saving thus saves more files than the asset you initially opened.

We intend to show the files that have changed in the "Changed Files" panel, where we only show git status today. Hopefully this will make the effects of saving more clear.

Thanks!

**Comment by AGulev** [comment]
@erikangelin-king ok, thank you
