### ISSUE TITLE
Can't synchronize

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1192]
### Actual behaviour
I can't syncronize, my changes.
If i use git in console i get fatal: Not a git repository (or any of the parent directories): .git
I have a .git folder in project folder
[.git.zip](https://github.com/defold/editor2-issues/files/1290495/default.git.zip)
### Steps to reproduce
I don't know. I am working, without any error. Then i want commit my changes. But editor don't see changed files, and can't be syncronized.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Defold sha</td><td>ead5b04fb115bb4a5d9d781b38d580d0fc4783b0</td></tr>
<tr><td>Build time</td><td>2017-09-08T14:12:54.646509</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13474 Compatibility Profile Context 22.19.162.4</td></tr>
<table>

**Comment by matgis-king** [comment]
It looks like your `.git` directory got corrupted somehow. There is supposed to be a file named `HEAD` in there that should contain the id of the latest commit, but it appears missing.

Probably the best course of action is to make a copy of the contents of your project directory without the `.git` folder, then do a clean import or checkout of your project from the server and copy your changed project files on top of that. After that, sync should hopefully work again.

I would be interested to know how you got into this situation. Do you think you got into this situation by using the Defold editor Sync feature, or could it have been caused by something else?

**Comment by d954mas** [comment]
Do you think you got into this situation by using the Defold editor Sync feature, or could it have been caused by something else? 
I don't sure that it is sync feature. When I press synchronization, it show me no changes. So maybe when I click first time sync, editor break git. Or maybe git break something else.

**Comment by erikangelin-king** [comment]
Can't reproduce, but please reopen if it happens again!
