### ISSUE TITLE
Strange search for images

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1203]
Search work is realy strange.

![2017-09-12_20-10-09](https://user-images.githubusercontent.com/2655263/30339090-94711644-97f6-11e7-9b77-5b905edebd5f.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Defold sha</td><td>ead5b04fb115bb4a5d9d781b38d580d0fc4783b0</td></tr>
<tr><td>Build time</td><td>2017-09-08T14:12:54.646509</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13474 Compatibility Profile Context 22.19.162.4</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! We don't use a traditional search algorithm that matches the exact input string. Instead, we've modelled the filter function on a Fuzzy Text Matching algorithm that was popularized by the [Sublime Text](https://www.sublimetext.com) text editor. Since then, it has been adopted by [Atom](https://atom.io), [Visual Studio Code](https://code.visualstudio.com), and many others.

Basically, as long as the characters appear in the path in the order you typed them, it will be included in the match. The matches are then scored by various criteria to determine its place in the results.

As you can see, the various `.png` images matched the input string but did not receive a very good score, putting them all on the bottom of the list. So I would say in this case the filter works as expected!

**Comment by d954mas** [comment]
Thanks, for explain
