### ISSUE TITLE
Add label.get_text (DEF-3016)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1422]
There is a gui.get_text so label.get_text is needed too.

Why this is useful is if you want to be able to dynamically set a GO label to something based on its current value set within the editor. For example if you want the value set in the editor to be a localization key.

**Comment by subsoap** [comment]
Getting metrics for labels would be useful too.

**Comment by andsveking** [comment]
Makes sense :)

Added an engine issue for this; DEF-3016

**Comment by paweljarosz** [comment]
So, for now there is get_metrics, but in metrics there is no text. One use case that I see and is very useful is to set the label text in the editor, so you can easily get it in runtime, modify, do something with it. It's useful because we do not have an option to use string for a go.property, so I thought I could create a label with a string I need and get it in the code, but there is no such function for labels sadly :/

**Comment by AGulev** [comment]
Solved in 1.2.160
