### ISSUE TITLE
Fuzzy search improvements [DEFEDIT-1370] [DEFEDIT-1371]

### ISSUE THREAD

**Issue by SebastienBellanger** [defold/editor2-issues#1473]
Fuzzy search is currently a bit too fuzzy. I've made a list of some improvements that could make it more useful :)

**Prioritize files that have an editor**
If I search for _pinata_bomb_, I get both _pinata_bomb.json_ and _pinata_bomb.lua_ in the result list. I would like my lua file to come up first in the list.

**Prioritize exact searches**
When i search for example for _main_ I would like to see main.* (eg main.lua, main.collection) at the top rather than anything containing main. Now I'm getting **ma**gnet_**in**ventory_icon.png at the top.

**Prioritize underscore and camel casing**
To make the underscore matching useful I think it should prioritize matching the first letter of each word of an underscore string. Eg. 'bib' should match with **b**ooster_**i**nventory_**b**utton.lua as it's first result rather than **bi**g_**b**ear_clicksound.wav

**Comment by matgis-king** [comment]
Good feedback!

**Comment by sicher** [comment]
Since fuzzy matching is used in completion, here are two cases where the current implementation scores wrong:

![screen shot 2018-03-21 at 09 50 03](https://user-images.githubusercontent.com/65613/37701268-9d8e088a-2cee-11e8-97db-15c0d260b8b7.png)

![screen shot 2018-03-21 at 09 50 28](https://user-images.githubusercontent.com/65613/37701214-70f3062c-2cee-11e8-92b1-61f7dd483987.png)

Trying to type "go.get()" results in "go.get_id()" since completion triggers on "(" and "go.get_id" is the first match. Typing "math.random()" yields the same result.
