### ISSUE TITLE
Updating a library dependency has no effect [DEFEDIT-1273]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1546]
### Expected behaviour
I should get the new version of a library dependency if I update the version (ie url) of a library dependency and fetch libraries again.

### Actual behaviour
I still see the old version in the editor

### Steps to reproduce
* Start the project with dependency: https://github.com/britzl/ludobits/archive/2.1.zip
* Notice that ludobits.m.util.lua has a lerp function and no clamp function
* Open game.project and change to https://github.com/britzl/ludobits/archive/3.0.zip
* Fetch libraries
* ludobits.m.util.lua still has a lerp and no clamp function
* Close Editor 2
* Open Editor 2
* Notice that ludobits.m.util.lua still has a clamp function and no lerp function

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Possibly related: #1472

**Comment by erikangelin-king** [comment]
Thanks for this report! There are two errors at play here.

First, the introduction of the new text editor exposed a bug in `Fetch Libraries`. Sometimes an exception was silently thrown and our view of what resources are present would be totally corrupt. This has been fixed in the next update.

Second, the new text editor caches suggested completions so you won't see suggestions from the new version of your require'd library until you've futzed around in the code a bit. We'll see what can be done about this.
