### ISSUE TITLE
Cannot see models if using tilemaps [DEFEDIT-1398]

### ISSUE THREAD

**Issue by andreas-strangequest** [defold/editor2-issues#1628]
### Expected behaviour
Models are sorted in Z-order just like Particles, tiles, sprites etc.
### Actual behaviour
Level designer cant place out 3D objects in a collection as they are always hidden underneath tilemap
### Steps to reproduce
Try to put gameobject with model in a collection together with a solid tilemap.

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-02T11:06:30.753964</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>659720155a36366288a3a20b7aacc7c73cdc9126</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.14.73</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Just merged a fix for this. The issue was that we first drew models, then tilemaps etc without depth testing, so the models would always end up underneath. As you're surely aware, how it looks in the engine depends on your render script. Note that the sample render script for models in the manual (https://www.defold.com/manuals/render/) always draws models on top of tilemaps etc, so if using that script there will still be a discrepancy between how it looks in the editor and the engine.
