### ISSUE TITLE
NullPointerException setting prototype of factory in War Battles

### ISSUE THREAD

**Issue by RantingBob** [defold/editor2-issues#1640]
### Expected behaviour

I'm not really sure, I was setting a prototype in a factory, doing the war battles tutorial

### Actual behaviour

I got a java.lang.NullPointerException: Unknown

### Steps to reproduce

I haven't been able to

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-02T18:10:50.863446</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9513f5404c2c6668a38b5415c549a869b65a27ff</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.30.14</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We'll try to repro this, let us know if it happens again.

**Comment by ShriekBob** [comment]
I can reproduce this, but, and this where shit get's weird, only if I'm trying to set the prototype of a factory, while connected to a VPN using Cisco Anyconnect, on MacOS, while the VPN is trying to reconnect after disconnecting due to network loss.  If I change any of those variables, the error goes away.

That is to say, if I'm not connected to the VPN, and I lose network access, no error
If I am connected to the VPN, and I choose to disconnect and reconnect manually no error
If I pick a different VPN software, no error
If I use Cisco Anyconnect on any other OS, no error.

I think we might want to qualify this as "WTF" and move on with our lives?

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144. Feel free to reopen in case it is still an issue.
