### ISSUE TITLE
BLOCKER!!! java.lang.OutOfMemoryError: java heap space [DEFEDIT-1301]

### ISSUE THREAD

**Issue by neonovoepsheno** [defold/editor2-issues#1643]
### Expected behaviour
Normal building of app.

### Actual behaviour
In the editor in progress of building app, we get a error from java.

### Steps to reproduce
Randomly, start conditions not defined.

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-05T11:33:32.956312</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5687f96313ec6f4b7bb914617b67764206ced10b</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"fac4ef14aacb4340a48ae9c256aadc75"'>fac4ef14aacb4340a48ae9c256aadc75</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 5450</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151.1008</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! Can you tell us a bit more about the project you're building? We need to have a look at the content to figure out what is taking so much memory.

If it is an internal project at King, you can provide us with any sensitive info on Hipchat through the **Defold Editor 2.0** channel. Otherwise, please send me a message on the Defold forum. I'm `mats.gisselson` there. We can discuss the details of your project there.

**Comment by neonovoepsheno** [comment]
@matgis-king 
Our project is Family Age. This happens not with all members of our team.

**Comment by matgis-king** [comment]
We've previously been allowed to access the `Family_Age_beta` project on the Defold dashboard. Is that the project that is giving the error?

**Comment by neonovoepsheno** [comment]
Yes

**Comment by matgis-king** [comment]
Thanks. Just to verify: It seems the last commit to that project is from December. Is that the same content you're building from and getting the error?

**Comment by neonovoepsheno** [comment]
No

**Comment by matgis-king** [comment]
We are unable to reproduce the error in the latest revision of the `Family_Age_beta` project. Would it be possible to get access to the latest content somehow?

**Comment by Morgerion** [comment]
I updated this build to the current state.
Here's how the error looks: https://www.dropbox.com/s/9vevw5mejailb0p/2018-02-07%2012.07.55.jpg?dl=0

**Comment by Morgerion** [comment]
How we tried to get rid of this:
- reboot the computer
- deletion java and Defold caches
- reinstall the Defold editor
- reinstall Java
- setting vmargs with different numbers -Xms and -Xmx
- update jre binaries in Defold

Tried to collect our other branches on the injured computer - did not help.

Actually, the same situation has been with our tester for 4 months already.
Despite all the updates during this time, the project is not building on him PC and no efforts to fix it failed.

Finally, today i got same bug on my PC. It's not funny, because since yesterday I have not had time to make any changes in the project - I just open editor it and start build.

**Comment by Morgerion** [comment]
I believe that it is not the content of the project that is to blame, but some configuration of the environment.

**Comment by matgis-king** [comment]
We've been able to reproduce the issue using the latest content. It looks like the error is caused by a frequently referenced Lua module requiring a missing module (`socket.smtp` required from `WstateSender.lua`). Due to the way the editor handles errors, it propagates up the dependency chain all the way up to the `game.project` resource, getting decorated with additional context along the way.

This is how it is supposed to work, but in this case it produces a huge number of error paths to the referencing Lua module, and the editor has to do a lot of work to figure out the root cause in order to present it.

I'm not sure why this only happens to some members of your team. Possibly the `socket.smtp` module exists on disk for some team members?

We're working on making the editor deal better with huge numbers of errors, but in the meantime fixing the broken require statement should hopefully get you back on track.

**Comment by Morgerion** [comment]
I put the "socket" source code in the project and fetch libraries.
Nothing helps.
Editor-2 works without problems for our two guys.
The other two can not build the project.
All have the latest version of the editor-2.

**Comment by matgis-king** [comment]
I just noticed the report came from a machine running Java version `1.8.0_161-b12`. This could be a differentiator. Editor 2 ships with a bundled JRE of version `1.8.0_102-b14`, but somehow the machine that reported this is using a different version. Perhaps something in the environment is overriding the Java version? Just a thought.

**Comment by Morgerion** [comment]
I reinstalled the JRE in order to resolve the error.
Now I have returned the original Defold JRE - nothing happens, bug is on his place.
I deleted all external modules (smtp / socket) from the project - it does not help.
I updated the project on defold console - now you can check it anew.

**Comment by Morgerion** [comment]
SOLVED
We're found a solution.
I removed the section [library] from the game.project, downloaded a new version of the editor-2 for the 64-bit Windows from the Defold site - it all worked.
Bug safely defeated.

**Comment by matgis-king** [comment]
Wow, I'm surprised you were able to use the 32-bit editor for as long as you have, considering the size of your project!

Thanks for letting us know! We will still look into memory usage and attempt to decrease how much memory is used during build, but knowing you are no longer blocked gives us a little breathing room.

**Comment by AGulev** [comment]
@matgis-king I have same bug with macos 64bit version
after 5-10 builds on big project (now with family age)
