### ISSUE TITLE
Scene picking does not work on some machines (cant move horizontally) [DEFEDIT-740]

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#166]
1. Add a collision object
2. Add a shape to it
3. try to move the collision shape horizontally
4. Also try to select the shapes in the editor view section

Actual result:
The collision shape cant be moved vertically.
And its not possible to select the shapes by clicking in the view pane you have to select them in outline
same thing for atlas objects.

**Comment by RagnarSvenssonKing** [comment]
To clarify, the underlying issue is that scene picking does not work. In this case, the Y-handle of the manipulator is always picked, thus locking the movement to the Y-axis. Similarly the shapes can't be selected because the Y-handle is always picked.
This was found on a machine that also had the issue where the ruler-labels are not rendered, but there is smudged white rendering (possibly the text) in the left margin.

**Comment by sofiahe** [comment]
I get the same behaviour on the linux laptop with ubuntu.

**Comment by RagnarSvenssonKing** [comment]
Quick win if we can use scissoring or something as simple as a work around.

**Comment by alexandru-p** [comment]
I get the same behavior on a Windows 10 x64 on 1.2.95  (7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e)

**Comment by ericroy** [comment]
I have this issue as well.  Makes it pretty hard to use the editor, since all coordinates have to be entered manually...

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>47641fce2a5efeecf842e55a0680b3a57d7a6951</td></tr>
<tr><td>Build time</td><td>2017-02-23T17:11:53.865708</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
The will hopefully be fixed now. A new build should appear during the day.

**Comment by ericroy** [comment]
Just got the update for this, works like a dream!  Thanks matgis

**Comment by matgis-king** [comment]
Yay! Thanks for trying it out!
