### ISSUE TITLE
error on sync the project

### ISSUE THREAD

**Issue by AlexarJING** [defold/editor2-issues#1914]
on the web page 
login failed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
in the message box of the editor
clojure.lang.ExceptionInfo: handler ':synchronize' in context ':global' failed at ':run' with message 'javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure'
com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
<hr/>

<table>
<tr><td>Build time</td><td>2018-05-23T09:28:32.990195</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>076e116ae09c690723ce05abbb953bfab55b606a</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9b318aace51c4ec9be2542549ca05704"'>9b318aace51c4ec9be2542549ca05704</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4400</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4474</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AlexarJING** [comment]
Is it because i am using shadowsocks for the internet connection?  There is no this error in prev version.

**Comment by erikangelin-king** [comment]
Hi @AlexarJING! We haven't changed anything in the editor related to login, we did however update our servers about a week ago. Our backend people are looking at it!

**Comment by nasthu** [comment]
"The failure occurred during the SSL handshake. The most likely cause for that is algorithm support."
https://blogs.oracle.com/java-platform-group/diagnosing-tls,-ssl,-and-https

What SSL algorithm does shadowsocks use? Java 8 uses TLSv1.2 as default.

I can't replicate this error and we are using standard AWS load balancing with an HTTPS listener, i.e. shadowsocks sets up an SSL connection with the AWS load balancer, so I don't think the problem is on our servers.

We are soon launching our own Defold email/password registration/login, I guess that will help you with the Google SSO problem :-)

**Comment by erikangelin-king** [comment]
Hi @AlexarJING! does this still happen? Perhaps you can try running the editor with debugging output as described here: https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md

**Comment by erikangelin-king** [comment]
Reopen if you need further help!
