### ISSUE TITLE
git broken

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2045]
### Expected behaviour
1)I don't know what happened. I work. There are no errors.
Then i want to commit. But git was broken.
git status
fatal: Not a git repository (or any of the parent directories): .git
editor says that i need create a repository
.git file https://yadi.sk/d/Cz7dhBdm3YwZ4a
### Steps to reproduce

<hr/>

<table>

<tr><td>Build time</td><td>2018-07-03T09:12:36.108133</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13506 Compatibility Profile Context 23.20.15002.11</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by Jerakin** [comment]
Was this your first commit? Which verison of git are you using?
It looks like you have two remotes, where are they pointing? One to the defold servers and one to github? There is a ORIG_HEAD in the folder but no HEAD, ORIG_HEAD is only created when a dangerous command is used, but the absense of HEAD makes me thing that the dangerous command went wrong. Did you do something in the repo before working? A destructive command or something?

**Comment by matgis-king** [comment]
Not only that, but the archive you sent seems to be missing some of the history. I tried creating a new `HEAD` file by copying `ORIGIN_HEAD` to `HEAD`, but it would could not recreate the working directory state from that due to missing parent objects. I tried the same thing with `master` by copying `refs/heads/master` to `HEAD`, but no luck there either.

At this point, I would suggest re-cloning the project from the origin. The local clone of the repo that you posted appears very broken indeed.

**Comment by d954mas** [comment]
I don't know what happened. It is not first commit. I use two remotes defold and git. I do not use any git command. I make fixes for game. Then i try to sincronize, but git was already broken. Previous commit was ok.
I reclone project, and all ok. But it was very strange.

**Comment by matgis-king** [comment]
Glad it got sorted out!
