### ISSUE TITLE
Particle editor stops reacting while particle system is being edited [DEFEDIT-1427]

### ISSUE THREAD

**Issue by spongepaddy** [defold/editor2-issues#2148]
### Expected behaviour
Particle editor does not stop reacting while particle system is being edited.

### Actual behaviour
Particle editor stops reacting while particle system is being edited.

### Steps to reproduce
Make a particle effect and edit a few values with the curve editor. Soon it's not possible to select anything in outline or properties (although the effect can still be toggled with the space-bar).

<hr/>

<table>
<tr><td>Build time</td><td>2018-08-15T15:09:04.180889</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>647b78d3829e45c0a9ab3b643d426a12feaba2da</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.10.14 310.42.25f02</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#2022 #1887

**Comment by erikangelin-king** [comment]
Note: Seems to be related to the size of the scene view. If you rearrange the panels so you get a small scene view, the properties window is less likely to hang. As if it takes too long to render the scene, and there is no time left in the 16ms budget to render the properties. The properties appear to still be there and react to input since once in a while you can activate a drop down by clicking around; it's just not re-rendered.

**Comment by erikangelin-king** [comment]
Workaround merged!
