### ISSUE TITLE
Long compiling times for native extensions (DEF-2410)

### ISSUE THREAD

**Issue by selimanac** [defold/editor2-issues#2278]
I love working on native extensions for Defold. But when my projects starts to grow, compiling C++ native extension with pre-build libs takes so long. It is almost impossible to adapt it to Defold. 
It would be nice to have local build solution.

**Comment by mathiaswking** [comment]
Hi @selimanac!
What platform are you compiling on?
How big are your extensions together? (source, library, jar files)

I don't think we'll release the libraries/sdk in the short term.

Currently, most platforms (except Android and HTML5), take less than 10 seconds to build. SO our next focus is the upload time.
What we are doing, is optimising the upload of files (e.g. big unchanged libraries etc), so that you don't have to wait for that twice. That also gives us other opportunities, for instance, if an unchanged extension needs to be built, we can cache it as well.

Some build steps are slow, for instance, the emscripten (HTML5) compiler is really slow, not much to do there I'm afraid. But the Android build step (which takes 10-15seconds) can be parallelized a bit, to make it a bit faster.

**Comment by selimanac** [comment]
Hi @mathiaswking 

Currently only for osx. But I'm planning to extend it to the other platforms.
I'm using prebuild c++ libs and their headers:
- OpenSSL(libssl, libcrypto and other openssl engines )
- [libuv](https://github.com/libuv/libuv)
- [uWebSockets](https://github.com/uNetworking/uWebSockets)

libs + headers: 9.6mb on disk.
Total project: 11.9 (with empty build folder and it is a almost empty Defold project just with a simple image and a one line script file)

This is the initial/minimum setup. I'm going to include a few more libs into it. 

It tooks approximately 1 minute to compile and run(variable to upload speed). 
As far as I understand, It uploads everything all the time. So if I change a single line on the base code even when I'm not changing the prebuild libs, I have to wait a minute to compile. 

In that case, caching would be great. At least for the prebuild libs.

Thank you.

**Comment by mathiaswking** [comment]
This should be live on the server now. Closing for now.
