### ISSUE TITLE
files can be closed without saving and there is no visual hint about them

### ISSUE THREAD

**Issue by MasihAkbari** [defold/editor2-issues#2281]
### Expected behaviour
asking about save or not save current file when i close changed file tab, therefore if i want to dismiss changes that i made to a file i have to press Undo button several times to reach the unchanged file

### Actual behaviour
you can close the file without save and when i close it there is no clue about that file being changed and not saved

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:54:27.240659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>GPU</td><td>GeForce GT 630M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.35</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! This is by design. You don't edit and save individual files, we consider the project itself to be the "document" that is edited. Thus, saving will save all changes.

It is done this way because you can perform edits to referenced scenes within a scene. For example, you can add components to a referenced game object directly from the Outline panel when editing a collection.

There is a little asterisk in the document tabs that indicate a resource has unsaved changes. In the future we hope to add a list of all edited files that have unsaved changes.
