### ISSUE TITLE
Different scene view and objects selection on various computers

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#2512]
I've noticed that the same scene (collection) looks different on my computers. Also there is a different behaviours in objects selection order when clicking on the scene.

**Illustration:**
**PC 1,** (an old ATI 7770 video card) Editor v: 1.2.148:
![2019-03-14_14-15-30](https://user-images.githubusercontent.com/842807/54411139-10e4f500-4710-11e9-98b4-91a120246f24.png)
(by the arrow I'm showing differents)
The same looks on my macbook (late 2015, 13", integrated video), Editor v:1.2.147:
![2019-03-14_14-27-22](https://user-images.githubusercontent.com/842807/54411212-602b2580-4710-11e9-9225-7e03c11daa12.png)

And selection behaviour on this computers:
https://youtu.be/wdBnxnmvufs

notice: When I've click on scene the editor always selecting backgrounds object with negative z-value except collections that placed above in an outline list. But this collection has objects above background object.

-----
**Other PC.** (specs below, GeForce 1050Ti) Editor v: 1.2.147
scene:
![2019-03-15_10-33-03](https://user-images.githubusercontent.com/842807/54411495-784f7480-4711-11e9-8d65-65e3557f9420.png)

and selection behaviour on this PC:
https://youtu.be/dO9zfrlylbc

When I'm clicking by scene the editor selects objects above backround. And this behaviour is prefer by me :)

<hr/>

<table>
<tr><td>Build time</td><td>2019-02-18T15:04:49.567122</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>5f1c6286a8bb1cfd8505517c1734f6d0666bf5df</td></tr>
<tr><td>Defold engine sha</td><td>5f1c6286a8bb1cfd8505517c1734f6d0666bf5df</td></tr>
<tr><td>Defold version</td><td>1.2.147</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 416.16</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Dragosha!
We've recently done large changes to how selection works, which is why you're seeing different selection behaviour between the editor versions.
For picking (clicking an object) we try to render the scene in the same order as usual, but use a special identifier color, which is then read back and translated to the actual object rendered. Then there are some rules for figuring out "what you actually ment". For instance, clicking a game object component (like a sprite) when inside a collection will be interpreted as an attempt to select the game object.
For box selection, we project aabb's of every rendered thing to screen space and then do a box intersection test + the "what you actually ment" thing.
It would be really helpful if we could get access to the project to debug this issue. Can you add me to your team? erik.angelin@king.com

**Comment by Dragosha** [comment]
Hi,
I guess Z-order of objects is main rule for selection. If I see an object above, then I picking it first.

Collection:
```
A (z=-100)
-- B (z=0) contains a sprite
C (z=0) contains a sprite
```
picking should select objects 'C'', not?

On examples, screens and selection behaviour looks beter from second PC, (1.2.147, stable).
I'll try to run 1.2.148 on this PC and compare.

**Comment by Dragosha** [comment]
Have made screencast of difference between 147 and 148 on one PC:
https://youtu.be/WSLlxuBhSwE

By me 147 is more correct.
Also sent invite to project to @erikangelin-king

**Comment by erikangelin-king** [comment]
Just merged a fix, we were not sorting the renderable stuff properly when picking. Please check if the new update performs picking the way you expect.
