### ISSUE TITLE
require vs inexistant modules

### ISSUE THREAD

**Issue by nadako** [defold/editor2-issues#2527]
The following is going to fail on building with `The file '/nope.lua' could not be found.`:

```lua
function init(self)
	if false then
		require "nope"
	end
end
```

If we prefix `require` with `_G` (so `_G.require "nope"`), running will work, but making a bundle will fail again.

I presume Defold scans for `require` calls to figure out what it wants to bundle, but this is not very sound in some cases. This issue was initially reported in https://github.com/hxdefold/hxdefold/issues/13. The problem there is that Haxe/Lua output does some conditional requires for compatibility with different `bit` libraries. And it only tries to do `require("bit32")` when `bit` is not found, which is never the case with Defold, however the bundling still fails because of the issue in question.

**Comment by matgis-king** [comment]
This is a tricky one. We do indeed scan the source code for `require` calls in order to figure out what files to include in the build. Even if the file is never loaded in some code paths, we must include it in the bundle if it can potentially be required. It is not really practical to perform sophisticated code analysis to determine whether or not a file can ever be loaded, since Lua affords many ways to decide this at runtime.

Now in the specific case of `bit32`, it is a built-in module in Lua 5.2. However, Defold runs LuaJIT, which does not have the `bit32` module. Potentially there could be Defold projects out there that contain a file named `bit32.lua` at the root level, and simply ignoring the require would break those projects. 

We also would prefer to keep treat references to missing files as build errors, since it is relatively common for developers to forget to commit files to the project, and it would be unfortunate if a game shipped with such an error at runtime.

As suggested, simply having a `bit32.lua` file at the project root works around the issue. Could this file perhaps be generated (unless already present) during the Haxe to Lua compile process as a workaround?

**Comment by nadako** [comment]
> Could this file perhaps be generated (unless already present) during the Haxe to Lua compile process as a workaround?

Yes, I think I'll go with that for the time being. It can also be fixed on the Haxe side: if the compiler will allow to substitute these "polyfill" snippets, I could just provide a Defold-specific one for `bit` directly in hxdefold.

**Comment by matgis-king** [comment]
Thanks for letting us know! I'll close the issue for now.
