### ISSUE TITLE
Defold Editor 2 does not start after update 1.2.149

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/editor2-issues#2534]
Defold does not start after update from 1.2.148 to 1.2.149 stable. Tried to update through the editor. Then I tried to download the editor from the site. When installing version 1.2.148, the editor works. OS Windows 10.
logs: [editor2.2019-03-29.zip](https://github.com/defold/editor2-issues/files/3022401/editor2.2019-03-29.zip)

**Comment by vlaaad** [comment]
Don't see any errors in logs unfortunately, but in 1.2.149 there was a known issue on windows that didn't allow updating, which fas fixed, and downloading editor from the [dashboard](https://www.defold.com/dashboard/) should help. Did it work for you?

**Comment by vlaaad** [comment]
In 1.2.149 we migrated editor from java 8 to java 11 (we provide our own jdk in installation), and if you have java installed, you still might have problems, because currently editor picks up java options from environment, and these might be incompatible (see [discussion on forum](https://forum.defold.com/t/defold-1-2-149-doesnt-start-on-windows/46791))

**Comment by sergeysinyavsky** [comment]
Thanks. The problem was in the environment. I changed jre1.8.0 to jdk-11.0.2. Then I changed JAVA_HOME and PATH environment. And the editor started.
