### ISSUE TITLE
[DEFEDIT-1691] Models not showing in viewport when multiple are in a scene using vertex-space-local in their material

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2614]
![2019-05-23 22_23_20-Defold Editor 2 0 - 3DTerrain](https://user-images.githubusercontent.com/409170/58309185-58df6280-7db8-11e9-913b-c0dbf555bdff.png)

**Comment by matgis-king** [comment]
Hi! Just tried this with and it appears to work with the built-in `model.material`. Presumably you are using a custom material?

When in `vertex-space-local`, your vertex program must transform the points and normals by the worldview and normal matrices, respectively.  Otherwise the mesh will always be drawn at the world origin, and normals will not respect object rotation.

Take a look at how the builtin `model.material` and `model.fp` are set up.

```glsl
// With vertex-space-local, these are not automatically transformed into world-space.
attribute mediump vec4 position;
attribute mediump vec3 normal;

uniform mediump mat4 mtx_worldview; // constant-type-worldview in material.
uniform mediump mat4 mtx_proj;      // constant-type-projection in material.
uniform mediump mat4 mtx_normal;    // constant-type-normal in material.

// Outputs to fragment program.
varying mediump vec4 var_position;
varying mediump vec3 var_normal;

// With vertex-space-world, mtx_worldview and mtx_normal will be identity matrices,
// so you can skip the transform. With vertex-space-local, you must apply them.
vec4 p = mtx_worldview * vec4(position.xyz, 1.0);
var_position = p;
var_normal = normalize((mtx_normal * vec4(normal, 0.0)).xyz);
gl_Position = mtx_proj * p;
```

**Comment by subsoap** [comment]
[main.zip](https://github.com/defold/editor2-issues/files/3216458/main.zip)

![2019-05-24 03_44_05-Defold Editor 2 0 - ModelErrorEditor](https://user-images.githubusercontent.com/409170/58322588-3fe5aa00-7dd6-11e9-9467-7fc1323c7a69.png)
![2019-05-24 03_43_58-Defold Editor 2 0 - ModelErrorEditor](https://user-images.githubusercontent.com/409170/58322589-3fe5aa00-7dd6-11e9-8d71-1befad3e0374.png)

Here is a sample for how it looks for me in editor on Windows 10. You can see that no custom material is being used.

**Comment by matgis-king** [comment]
Ah, I see now. The bug only surfaces when you have a `.model` file that you reference from multiple game objects. If each game object has its own embedded model component, it works.

**Comment by matgis-king** [comment]
A fix has been merged. Thanks for reporting!

**Comment by subsoap** [comment]
![2019-05-27 11_55_07-Defold Editor 2 0 - 3DTerrain](https://user-images.githubusercontent.com/409170/58435665-66297500-8076-11e9-9441-5c116182e5ed.png)

Fix in next version?

**Comment by matgis-king** [comment]
Looks like you're on the stable channel. This probably happened due to a mistake we made a while back that causes most users to end up on the stable channel. The stable channel is only stable in the sense that you'll get far less frequent updates to the editor. Currently we don't do additional testing to ensure that it works better than the regular version.

If you redownload the editor from the dashboard you'll get back to more frequent editor updates. The engine part of the editor will remain stable, so you should feel secure about using it in production.

**Comment by subsoap** [comment]
Yep, appears to be working now.

![2019-05-29 14_54_51-Defold Editor 2 0 - 3DTerrain](https://user-images.githubusercontent.com/409170/58594177-d0324d80-8221-11e9-89be-3a9b8c17bc96.png)
