### ISSUE TITLE
Cant build on windows 7 missing dll file

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#291]
![image](https://cloud.githubusercontent.com/assets/22887289/21013786/9cc3e112-bd5b-11e6-8f45-3e447eddce94.png)

Defold version: 1.2.95
Defold sha: a89c5c502c53dae7788f2781bba29685e166d1d2
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
If I recall correctly they talk about this on an episode of handmade hero (https://www.youtube.com/watch?v=J3y1x54vyIQ). If you want the games to run on as many machines as possible you are much more likely to get it to work with XInput 1.3 rather than 1.4 since it is available on way more machines. Otherwise you will require players to install a bunch of stuff in order to play the game (and run the editor). And you are also better off if you load the dll dynamically.

**Comment by erikangelin-king** [comment]
We accidentally bumped the requirements to Windows 8.1 - this will be fixed asap!

**Comment by RagnarSvenssonKing** [comment]
Fixed
