### ISSUE TITLE
Cant replace files in the Assets section by dragging them and clicking replace button in prompt [DEFEDIT-735]

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#299]
1. Create two asset folders, A (main) and B (Level)
2. In both folders create a folder C (images)
3.  Add two png in the C folder in A
4. Drag the folder C  in A to B folder
5. Click replace button

Or create two atlast files in different folders.
Drag one to replace the other.

Actual result:
Nothing happens. The files are not replaced, no files are removed. All stays in the original place.

![replace](https://cloud.githubusercontent.com/assets/22887289/21049854/71101cd6-be17-11e6-8051-be7bbe3e26ce.gif)

Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by sofiahe** [comment]
Can still reproduce in 6adb0f1ceea31b5fe5ea874aaab410c3ef14f8db

**Comment by matgis-king** [comment]
This issue was originally found before we reported exceptions thrown inside handlers, and so the action would appear to have no effect, but it would in fact have caused an error that would leave the in-memory project in a broken state.

I believe the "replace atlas" repro shown in the animation is not sufficient in isolation, but a result of the original "folder merge" attempt - from that point on, many file operations would silently fail.

I cannot reproduce this by attempting the "replace atlas" repro after opening the project, but the original "folder merge" repro is still reproducible, although now it will show an error dialog. After that, I get similar error dialogs whenever I try various file operations.

I reported this as issue #462, which I now believe is the same as this one. I prefer to keep both issues since they contain slightly different information.
