### ISSUE TITLE
[IMPROVEMENT] No proper error message is shown when trying to import a deleted project

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#314]
It can be noticed that when trying to import a deleted project, no proper error message is shown.
![importing deleted project png](https://cloud.githubusercontent.com/assets/23701955/21101051/fb3032ba-c07f-11e6-988e-15f7312e0dfd.png)

Steps to reproduce:
1. Open the Editor
2. Click Import a project
3. In a browser, go to the defold dashboard and delete a project
4. In the editor, try to import the deleted project

**Comment by AGulev** [comment]
now it shows an error
<img width="555" alt="image" src="https://user-images.githubusercontent.com/2209596/50633686-7e281d00-0f4c-11e9-85d2-f0835d047b13.png">



### Expected behaviour

### Actual behaviour

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-12-18T15:04:58.078787</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e6badbdfbe3d296da36f9f8e2e4848ffdfb9a971</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ba8ab208e1ea4a25aaec1a52f46a9cbb"'>ba8ab208e1ea4a25aaec1a52f46a9cbb</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.0.36</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14</td></tr>
<table>

**Comment by britzl** [comment]
Dashboard has been removed.
