### ISSUE TITLE
Rebuild?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#363]
Are projects always rebuilt now? There is only Build as an option, no Rebuild.

**Comment by AGulev** [comment]
yea, very much missing the option to rebuild

**Comment by AGulev** [comment]
@ragnard-king really wait this feature.
We work together with gamedesigner, and offten when I making some changes with atlases, my gd should restart editor after pull or sync (because e2 has no rebuild)
Especially when my change touches textures/atlases. We recieve errors with removed textures or if build starts we have problems with position of sprites in textures. All this problems resolves after restart of editor. It really not convenient. 
I think, rebuild feature can help with it.

**Comment by RagnarSvenssonKing** [comment]
Thanks for letting us know, we will investigate!

**Comment by Malmer** [comment]
Since cache invalidation is a really hard problem, I really think a full rebuild should be possible through the menu options. Even if the intent is to make a fully bug free software, I feel that forcing a rebuild often solves a lot of issues. It is also a good thing to do before committing. Making sure that what I have isn't influenced by some old cached files that may be in my build folder.

**Comment by RagnarSvenssonKing** [comment]
Fixed! A caveat is that the rebuild is not a true rebuild (which would require us to completely reload the project from disk).
