### ISSUE TITLE
Main.collection error [DEFEDIT-679]

### ISSUE THREAD

**Issue by CoCopia** [defold/editor2-issues#376]
### Expected behaviour
Opening Main.collection in editor 2
### Actual behaviour
failed with java.lang.NullPointerException: Unkown.
### Steps to reproduce
Would need to open my personal project main.collection, which opens in editor 1. This is reason my project fails to compile in editor 2, but is good in editor 1
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>1feae82a89229f71aafe6770a656a3cbfcdcdfe3</td></tr>
<tr><td>Build time</td><td>2017-01-05T19:13:37.583240</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a998bd8c195742d6bbdc43a08ea93bb3'>a998bd8c195742d6bbdc43a08ea93bb3</a></td></tr>
<table>

**Comment by matgis-king** [comment]
The issue seems to be that certain Spine exporters output bad values for step-interpolated animation curves. We've seen this with DragonBones 4.9.5, and have reported the issue. If your Spine `.json` file was exported from DragonBones, you might be able to fix it by opening it in a text editor and replacing all occurrences of `"curve":null` with `"curve":"stepped"`.

A fix is on the way that will allow you to open scenes that contain malformed Spine scenes in editor 2, but the offending curves will fall back on using linear interpolation.

**Comment by matgis-king** [comment]
The fix has been merged into our development branch, and a new build should be produced during the day. Thanks for reporting!

**Comment by CoCopia** [comment]
Wow, now thats quick.
