### ISSUE TITLE
Annoying flashing popup when you refocus on editor window

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#386]
1. Have the editor open
2. Move focus to another application on your computer
3. Move focus back to the editor

Actual result: A flashing popup window, which you dont see what it says. it just flashes by all the time. Very annoying.
![flashingpopup](https://cloud.githubusercontent.com/assets/22887289/21892539/a014568e-d8d7-11e6-8018-435835a13fe3.gif)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by AGulev** [comment]
This issue very annoying when working with other editor (Atom for ex.)

**Comment by AGulev** [comment]
@erikangelin-king 
Small clarification:
The main problem of issue that shortcut don't work after this flashing popup.
On mac is't looks like 
![2017-01-14_12-19-39](https://cloud.githubusercontent.com/assets/2209596/21953880/bf5addd8-da53-11e6-80c4-fa0777787e6c.png)
instead of 
![2017-01-14_12-20-13](https://cloud.githubusercontent.com/assets/2209596/21953883/d410143c-da53-11e6-89b9-ddaf049ca20e.png)

And I need to click to other editor windows (for ex. Assets or Change files) for restore focus and then shortcuts works fine

**Comment by ragnard-king** [comment]
A fix has been merged and will be available as an update shortly.
