### ISSUE TITLE
Can't build project from editor 1

### ISSUE THREAD

**Issue by GerodruS** [defold/editor2-issues#539]
### Expected behaviour
Game is running

### Actual behaviour
Windows with error:
"java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production ctx) [node-id label]))"
Main game window contains standard message: "Defold. Waiting for connection..."

### Steps to reproduce
Sorry, I'm trying to localize the problem, but project does not a small one ):

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>f0eb8c8d2b6c93be94ca3421f75f698d0a08b3f7</td></tr>
<tr><td>Build time</td><td>2017-02-27T18:01:54.924639</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=50ed04f5b0524d50b1cfaf59bac9f163'>50ed04f5b0524d50b1cfaf59bac9f163</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! I think this is because there is a dependency cycle. A collection contains an embedded game object with a collection factory (same thing happens with a collection proxy), and that factory uses some ancestor collection as prototype. For instance foo.collection contains a game object with a collection factory using foo.collection as prototype. Eventually we should detect cycles like this and report them more nicely :)

**Comment by erikangelin-king** [comment]
duplicate https://github.com/defold/editor2-issues/issues/365
