### ISSUE TITLE
Editor2 discard all changes in project [DEFEDIT-857]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#612]
### Expected behaviour
Possibility to work in both editors same time
### Actual behaviour
All changes what I made in editor 1 (but not pushed) was discarded when I open editor 2.
### Steps to reproduce
I don't know haw to reproduce it, but in my case it was:
1. I made new branch in SmartGit 
2. I made changes in game.project file and many other *.gui files.
3. I started Editor 2 and open same project in same folder
4. Editor ask about updates  - >  apply it
5. After restart editor ask about updates one more time - > apply it
6. Editor starts. And I saw that I have no all my changes. In editor1 the same situation. 
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>9b835c018e20c8f541b70df888d1b65725771244</td></tr>
<tr><td>Build time</td><td>2017-03-22T10:31:57.897209</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
When you opened the project in Editor 2, did you happen so see if the changes were there before you applied the update?

**Comment by AGulev** [comment]
I don't know. (
Editor ask to update, and I just did it.

**Comment by matgis-king** [comment]
Thanks! I'm trying to gather more info in order to figure out how this could happen. Another question: Are you certain you saved your changes to the `game.project` file and the `*.gui` files before you opened the project in Editor 2? If the changes were never seen by Editor 2, they might have been lost when Editor 2 saved the project before installing an update.

**Comment by AGulev** [comment]
Yes, all changes was saved, I'm sure because I'm worked few hours in editor1 and saw them in "Changed Files" window.
Changes was not pushed (synchronized), but saved.

**Comment by matgis-king** [comment]
OK, thanks for checking. We found an issue where the "Update Available" dialog would stop Editor 2 from detecting external changes to the project while it was open. Then, when you'd choose to install the update it would save the project, overwriting any external changes that had happened since the "Update Available" dialog showed up. If you had Editor 2 sitting around displaying the "Update Available" dialog unanswered while you made changes in Editor 1, it could potentially revert your project. Do you think that could explain what happened here?

**Comment by AGulev** [comment]
I think yes.
Looks like my issue.

**Comment by matgis-king** [comment]
Thanks for your help! We have a fix that should make it in very soon. Sorry about your lost work. 😢

**Comment by AGulev** [comment]
No problem, it is unpleasant but not an apocalypse.
Just training of my patience =)  And second time remake much easier and faster.

**Comment by matgis-king** [comment]
A fix has been merged. Thanks for reporting!
