### ISSUE TITLE
Editor doesn't build with updated resources

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#687]
### Expected behaviour
Changed content in Gui should be reflected when game is built

### Actual behaviour
It isn't, game is in an previous state

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>eb6c764ede93df308853ccbf12496487e3683f0e</td></tr>
<tr><td>Build time</td><td>2017-04-13T16:23:46.350160</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=3851571eb5c04bef83a3f5895540b7c7'>3851571eb5c04bef83a3f5895540b7c7</a></td></tr>
<table>

**Comment by Jerakin** [comment]
Solved, collection proxy missing a collection.

Opened project in editor1 and found it directly

**Comment by ragnard-king** [comment]
I believe this issue is two things:
1. We previously had a bug where we would incorrectly launch game even though something failed during build (either a build error or an internal error). That has since been fixed.
2. We did not validate that collection proxies have a valid collection assigned. This is addressed by https://github.com/defold/defold/pull/1639

**Comment by ragnard-king** [comment]
Fix for collection proxy validation on build merged, coming in update shortly.
