### ISSUE TITLE
Collection with one-polygon mesh (attached) shows vertex buffer error in viewport

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#794]
The mesh previously worked, but doesn't anymore since a recent update.

Mesh is only a single tiny triangle used for full screen rendering of render targets.

[screen_triangle.zip](https://github.com/defold/editor2-issues/files/991394/screen_triangle.zip)

**Comment by subsoap** [comment]
How recent of an update? Just today?

Try this one?
[quad.zip](https://github.com/defold/editor2-issues/files/991659/quad.zip)

**Comment by RagnarSvenssonKing** [comment]
Sorry, fixing right away!

**Comment by RagnarSvenssonKing** [comment]
The fix that broke your triangle was validation code of the collada scene. It turns out that screen_triangle.dae is invalid:
<input semantic="VERTEX" source="#Plane-mesh-vertices" offset="0"/>
<input semantic="NORMAL" source="#Plane-mesh-normals" offset="1"/>
<input semantic="TEXCOORD" source="#Plane-mesh-map-0" offset="1" set="0"/>
(notice that both normal and texcoord share offset 1)
Indices:
<p>0 0 1 1 2 2</p>
(meaning both normal and texcoord have indices [0, 1, 2])
But the normal has only one entry, i.e. 1, 2 is out of bounds:
<float_array id="Plane-mesh-normals-array" count="3">0 0 1</float_array>
...
<accessor source="#Plane-mesh-normals-array" count="1" stride="3">

Previously, the editor clamped the indices to the available array, which is why it worked. After I imported it into blender and re-exporting to Collada, it some how patched the scene to have split  indices for normals/texcoord, with 0 as index for every normal:
<input semantic="VERTEX" source="#Plane-mesh-vertices" offset="0"/>
<input semantic="NORMAL" source="#Plane-mesh-normals" offset="1"/>
<input semantic="TEXCOORD" source="#Plane-mesh-map-0" offset="2" set="0"/>
(split indices for normal/texcoord)
<p>0 0 0   1 0 1   2 0 2</p>
(0 index for every normal)

So you can quickly patch the dae file to make it work. How did you obtain the file, what tool did you use to export it?

**Comment by Malmer** [comment]
The file was made manually in a text editor, which explains the (human) error. Thanks.
