### ISSUE TITLE
Refresh option for Changed Files and Assets menus.

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#799]
Would be great to have refresh option for those menus.
It would be useful in many cases, but my offen case is:
1. Make some changes in project;
2. Push the changes using other git client;
3. Files still marked as Changed Files.

Sometimes menu make an automatic refreshing (but I dont know why) but sometimes helps only editor restart.

**Comment by matgis-king** [comment]
You shouldn't have to refresh the view manually. We found and fixed an issue where we did not detect certain types of changes made externally. Now the view will reflect the current Git state when you return to the editor.

I hope this will eliminate the need for a Refresh button, but feel free to reopen otherwise!
