### ISSUE TITLE
Tried to open script file in external editor

### ISSUE THREAD

**Issue by drhayes** [defold/editor2-issues#927]
### Expected behaviour

Right-clicked script file in Assets tree and selected "Open As > External Editor". I was hoping I could use Sublime Text 3 as my external.

### Actual behaviour

The stack trace you see before you!

### Steps to reproduce

Honestly not sure. Had never used Editor 2 before (previous version I tried wouldn't boot, went back to the safety of Editor 1 for a week or two). Editor 1 has proper config to edit scripts in ST3.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>3d99c6c581c4d8f017e0c334f4b97abaf47bf3c5</td></tr>
<tr><td>Build time</td><td>2017-05-23T16:02:03.884357</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=072e27f11536472d82558548b6c9aaf3'>072e27f11536472d82558548b6c9aaf3</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Hi @drhayes,

Thanks for the report.

This could be caused by ".script" files not being associated with any application on your system. Have you associated ".script" files with Sublime? If not, try navigating to an arbitrary ".script "file in finder, right-click, "Get Info" and under "Open With", make sure "Sublime" is selected. You can also set a specific code editor in "Preferences > Code".

We should definitely give a better error message in this case.

**Comment by drhayes** [comment]
Yup, that fixed it! Thanks!

**Comment by ragnard-king** [comment]
Great to hear that! Downgraded to minor as we should handle the error better.

**Comment by erikangelin-king** [comment]
Better error message in place
