### ISSUE TITLE
Editor keeps freezing when clicking to expand a folder

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#943]
Just 100% freeze no error. When it happens seems to be random just after the editor being open and working long enough. So far it has happened 3 times when clicking to expand a folder in Assets panel over the last few hours.

![2017-05-26 14_56_23-defold editor 2 0 - defrs not responding](https://cloud.githubusercontent.com/assets/409170/26513977/8af770a0-4223-11e7-99f5-8fc3ef1887bb.png)

Could be related to hdd not responding fast enough and it not being able to recover from a delay.

**Comment by ragnard-king** [comment]
Hi @subsoap. I think I've reproduced this on Windows. The issue I'm seeing is that expanding a folder in asset browser sometimes freezes for a few seconds, then editor resumes and works as normal. Is that the same issue you're seeing?

**Comment by subsoap** [comment]
When it has happened for me it completely locked up the editor and leaving it to sit for a few minutes did not help.

**Comment by ragnard-king** [comment]
Oh, ok, that's different and worse. From looking at other issues, it seems like you've quite frequently experienced the editor locking up on Windows. Do you have a full Java JDK installed by any chance? If so, it would be really helpful if you grab a thread dump when the applications locks up. This can be done with the `jstack` tool like this:

```
C:\Program Files\Java\jdk${jdk-version}\bin\jstack -l ${pid of defold editor process} > C:\threaddump.txt
```

Which version of Windows are you running?

**Comment by Dragosha** [comment]
I have the same issue on my PC with Windows 10.

**Comment by ragnard-king** [comment]
@Dragosha Thanks for reporting. Is it the issue with the asset browser specifically, or the editor locking up in general?

**Comment by Dragosha** [comment]
@ragnard-king usally with the asset browser. But once have freezing when expand folder in outline panel.
Windows task manager shows this issue as "defold/java not response"

**Comment by ragnard-king** [comment]
@Dragosha Ok thanks. If this happens to you again, a thread dump would be most helpful.

@Dragosha @subsoap If you have time to help with a thread dump, you can download a JDK from: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Then run: `C:\Program Files\Java\jdk1.8.0_131\bin\jstack -l {pid}` as I described above.

**Comment by Dragosha** [comment]
@ragnard-king thread dump:
[threaddump.txt](https://github.com/defold/editor2-issues/files/1038210/threaddump.txt)

**Comment by ragnard-king** [comment]
@Dragosha Thanks! Just to double-check, was that thread dump taken when the editor application was in a locked/unresponsive state?

**Comment by Dragosha** [comment]
@ragnard-king yes, I grabbed it after the editor is freeze

**Comment by ragnard-king** [comment]
@Dragosha Excellent!

**Comment by ragnard-king** [comment]
Unfortunately the thread dump did not give much information. Can you describe more about what 
you were doing before/when the editor frooze? For example, were you working with a specific resource type (script, particlefx, etc) or did you change something in an external program?

I've tried to reproduce this on a Windows 10 computer but I can't, which makes it very hard to fix...

**Comment by Dragosha** [comment]
@ragnard-king hello, not sure that it would help, but I got video with this issue two times in a row:
https://youtu.be/tvNDPxoLdfU?t=1m14s
at 1:14
and at 2:40

**Comment by ragnard-king** [comment]
Thanks to some very helpful testing by @Dragosha we've found a likely cause for this issue, a relatively reliable repro, and a possible workaround:

This issue seems to be similar to an old JavaFX bug [JDK-8132897](https://bugs.openjdk.java.net/browse/JDK-8132897) which was caused by a combination of having a touch screen or a tablet attached and clicking an out-of-focus control. That bug has been fixed but it seems like a similar bug could still be present for the tree control we are using.

**Repro:**
1. Open project
2. Open main collection
3. Open some `.font` and click to size in properties panel so properties panel has focus
4. Click directly on arrow to expand "buitins" in asset panel without first focusing anywhere in the asset panel
5. Freeze!

**A workaround is to:**
1. Open `Defold/config` in text editor
2. On the line that starts with `vmargs = ...` add `,-Dglass.accessible.force=false` at the end of the line
3. Restart editor

Note that the config file is overwritten after each update, so if you update you need to change the config file again.

@subsoap Do you have a touch screen or tablet device of some sort connected? If possible, it would be great if you tried the workaround above.
