### ISSUE TITLE
Fail to generate macos bundle (You must specify a template error)

### ISSUE THREAD

**Issue by hwangroman** [defold/editor2-issues#954]
### Expected behaviour
Able to generate a macOS bundle

### Actual behaviour
Fails with build error message: you must specify a template

### Steps to reproduce
Run Project->Build->macOS application

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>9abfcf220d13d05cf85a13e85e43bdb46c8d8d99</td></tr>
<tr><td>Build time</td><td>2017-05-30T14:27:29.813197</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
I would assume you have a gui-file with a template node where you have forgotten to specify which gui-scene to use as a template? Do you get any indication in the error which file it is? The background to this issue is that we currently use two different content pipelines when bundling the game as opposed to running the game on the local machine. The local pipeline obviously has a bug where it doesn't tell you that there is an error.

**Comment by hwangroman** [comment]
There was no indication of which file caused the build error. But after your comment, I found the unused template and removed it. The issue is solved. But it would be great to add a filename indicator.

**Comment by RagnarSvenssonKing** [comment]
I agree, I added this issue to reflect the remaining bug: https://github.com/defold/editor2-issues/issues/975
